#!/bin/sh
# 容器启动时根据环境变量生成前端运行时配置 /usr/share/nginx/html/env.js，
# 由 public/index.html 中的 <script src="/env.js"> 加载（见 src/config.js）。
set -e

: "${DOMAIN:=}"
: "${SCHEME:=http}"

if [ "$SCHEME" = "https" ]; then
  WS_SCHEME="wss"
else
  WS_SCHEME="ws"
fi

# 未显式设置 DOMAIN 时输出 $ORIGIN 占位符，前端会替换为访问页面所用的
# host:port（src/config.js 的 resolveHost），局域网/公网 IP:端口 直达即可用。
if [ -n "$DOMAIN" ]; then
  WS_BASE="$WS_SCHEME://$DOMAIN"
  API_BASE="$SCHEME://$DOMAIN"
else
  WS_BASE="$WS_SCHEME://\$ORIGIN"
  API_BASE="$SCHEME://\$ORIGIN"
fi

: "${WS_URL:=$WS_BASE/ws/}"
: "${LOBBY_URL:=$WS_BASE/lobby/}"
: "${API_URL:=$API_BASE}"
: "${AVATAR_URL:=$API_BASE/avatars/}"

cat > /usr/share/nginx/html/env.js <<EOF
// generated by docker/entrypoint.sh at container start
window.__ENV = {
  WS_URL: "$WS_URL",
  LOBBY_URL: "$LOBBY_URL",
  API_URL: "$API_URL",
  AVATAR_URL: "$AVATAR_URL"
};
EOF
