#!/bin/sh
# 容器启动时根据环境变量生成前端运行时配置 /usr/share/nginx/html/env.js，
# 由 public/index.html 中的 <script src="/env.js"> 加载（见 src/config.js）。
set -e

: "${DOMAIN:=localhost}"
: "${SCHEME:=http}"

if [ "$SCHEME" = "https" ]; then
  WS_SCHEME="wss"
else
  WS_SCHEME="ws"
fi

: "${WS_URL:=$WS_SCHEME://$DOMAIN/ws/}"
: "${LOBBY_URL:=$WS_SCHEME://$DOMAIN/lobby/}"
: "${API_URL:=$SCHEME://$DOMAIN}"
: "${AVATAR_URL:=$SCHEME://$DOMAIN/avatars/}"

cat > /usr/share/nginx/html/env.js <<EOF
// generated by docker/entrypoint.sh at container start
window.__ENV = {
  WS_URL: "$WS_URL",
  LOBBY_URL: "$LOBBY_URL",
  API_URL: "$API_URL",
  AVATAR_URL: "$AVATAR_URL"
};
EOF
