/**
 * Standalone all-in-one mode: a single Node process on a single port that
 * serves the built frontend (dist/), the HTTP API and both WebSocket
 * channels. Used by Dockerfile.standalone.
 *
 *   PORT        listen port (default 8080)
 *   DIST_DIR    location of the built frontend (default ../dist)
 *   DOMAIN      public host[:port] of this instance (default localhost)
 *   SCHEME      http | https - https makes the frontend use wss (default http)
 *   WS_URL / LOBBY_URL / API_URL / AVATAR_URL  override generated env.js
 *
 * The frontend reads /env.js at runtime (see src/config.js); it is
 * (re)generated on every start from the variables above.
 */
const http = require("http");
const fs = require("fs");
const path = require("path");
const RoomManager = require("./rooms");
const GameServer = require("./gameServer");
const LobbyServer = require("./lobbyServer");
const HttpApi = require("./httpApi");
const { serveStatic } = require("./staticFiles");

const PORT = Number(process.env.PORT) || 8080;
const DIST_DIR =
  process.env.DIST_DIR || path.join(__dirname, "..", "dist");

// --- generate the frontend runtime config -------------------------------
const domain = process.env.DOMAIN || "localhost";
const scheme = process.env.SCHEME || "http";
const wsScheme = scheme === "https" ? "wss" : "ws";
const envJs = `// generated by standalone.js at container start
window.__ENV = {
  WS_URL: ${JSON.stringify(process.env.WS_URL || `${wsScheme}://${domain}/ws/`)},
  LOBBY_URL: ${JSON.stringify(process.env.LOBBY_URL || `${wsScheme}://${domain}/lobby/`)},
  API_URL: ${JSON.stringify(process.env.API_URL || `${scheme}://${domain}`)},
  AVATAR_URL: ${JSON.stringify(process.env.AVATAR_URL || `${scheme}://${domain}/avatars/`)}
};
`;
fs.writeFileSync(path.join(DIST_DIR, "env.js"), envJs);

// --- wire up services -----------------------------------------------------
const roomManager = new RoomManager();
const game = new GameServer(roomManager);
game.createWss();
const lobby = new LobbyServer(roomManager);
lobby.createWss();
const api = new HttpApi();

const server = http.createServer((req, res) => {
  const { pathname } = new URL(req.url, "http://localhost");
  if (
    pathname === "/healthz" ||
    pathname === "/dynamic/init" ||
    pathname === "/upload/avatar" ||
    pathname.startsWith("/avatars/")
  ) {
    return api.handleRequest(req, res);
  }
  serveStatic(DIST_DIR, req, res);
});

server.on("upgrade", (req, socket, head) => {
  const pathname = req.url.split("?")[0];
  if (pathname.startsWith("/lobby")) {
    return lobby.handleUpgrade(req, socket, head);
  }
  // game channel: /ws/{channel}/{playerId}[...] (or without the /ws prefix)
  game.handleUpgrade(req, socket, head);
});

server.listen(PORT, () => {
  console.log(`[standalone] all-in-one server listening on :${PORT}`);
  console.log(`[standalone] serving frontend from ${DIST_DIR}`);
});
